version: 1.9.5
name: Companions
main: me.astero.companions.CompanionsPlugin
author: Astero
description: Create & fully customize your own companions, then allow players to buy it!
api-version: 1.13
softdepend: [Vault, PlaceholderAPI, CompanionsAPI]
commands:   
  companions:
    aliases: [c]
    description: opens up the main GUI.
  givecompanion:
    aliases: [givec]
    description: gives the specified player the specified Companion. Setting true makes it so it gives it as an active Companion.
  removecompanion:
    aliases: [removec]   
    description: removes the specified Companion from the specified Player.
  givecompanionitem:
    aliases: [givecitem]
    description: gives the player the specified plugin item.
  clearcompaniondata:
    aliases: [ccdata]
    description: if a player is specified, it'll only delete that player's data. If all is inputted, it'll delete EVERYONE's data. (Use with caution, you can NOT get back your data)
  forceupgrade:
    description: forces an upgrade upon specified player. (does not make player pay the upgrade fee).
  forceactive:
    description: forces an owned Companion onto the specified player.
  tradecompanion:
    aliases: [tradec]
    description: trades the specified Companion to the specified player.
  forcedeactive:
    description: forces the specified player's active Companion to be removed.
  companioncoin:
    aliases: [ccoin, cc]
    description: manage/view companion coins.
